version: "3.9"
   
services:
  db:
    build: .
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=web
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migration:
    image: ubc-course-explorer_web
    container_name: migrations
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=web
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - migration
  