# Generated by Django 3.1.1 on 2020-12-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='corequisites',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='corequisites_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='dependencies',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='distributions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='five_year_average',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_credits',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='prequisites',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequistes_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='standard_deviation',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
