# Generated by Django 3.1.1 on 2020-12-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0002_auto_20201228_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prequisites',
            new_name='prerequisites',
        ),
    ]
