# Generated by Django 3.1.1 on 2021-01-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0003_auto_20201228_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='distributions',
            new_name='distribution',
        ),
        migrations.AddField(
            model_name='course',
            name='distribution_term',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
