# Generated by Django 3.1.1 on 2021-01-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0007_course_fdsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fdsa',
        ),
    ]
