# Generated by Django 3.1.1 on 2021-01-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0008_remove_course_fdsa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='sub_name',
        ),
    ]
