# Generated by Django 3.1.1 on 2021-01-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0009_auto_20210101_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='latest_grade_distribution',
            new_name='distribution',
        ),
    ]
