# Generated by Django 3.1.1 on 2021-01-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0010_auto_20210102_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(default='0', max_length=2000),
        ),
    ]
