# Generated by Django 3.1.1 on 2021-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0011_auto_20210103_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=''),
        ),
    ]
