# Generated by Django 3.1.4 on 2021-01-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0011_auto_20210103_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='maximum_grade_average',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='minimum_grade_average',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
