# Generated by Django 3.1.1 on 2021-01-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0012_auto_20210103_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
