# Generated by Django 3.1.1 on 2021-01-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0013_auto_20210103_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='average',
        ),
    ]
