# Generated by Django 3.1.13 on 2021-07-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0016_auto_20210723_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor_ratings',
            field=models.TextField(default='err'),
        ),
        migrations.AddField(
            model_name='course',
            name='sections_teaching_team',
            field=models.TextField(default='err'),
        ),
    ]
