# Generated by Django 3.1.1 on 2021-01-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0005_auto_20210101_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='distribution',
            new_name='latest_grade_distribution',
        ),
    ]
