# Generated by Django 3.1.1 on 2021-01-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0006_auto_20210101_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fdsa',
            field=models.CharField(default='', max_length=200),
        ),
    ]
