# Generated by Django 3.1.4 on 2021-01-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0012_auto_20210103_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='maximum_grade_average',
            new_name='highest_average',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='minimum_grade_average',
            new_name='lowest_average',
        ),
    ]
