# Generated by Django 3.1.13 on 2021-07-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetracker', '0017_auto_20210724_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite_tree',
            field=models.TextField(default='err'),
        ),
    ]
