# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, on push to main
#
# Adapted from GitLab CI given in https://testdriven.io/blog/deploying-django-to-ec2-with-docker-and-gitlab/

on:
  push:
    branches: [ main ]

name: Deploy to Amazon EC2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create .env.prod
      id: create-env-file
      run: |
        echo DEBUG=0 >> .env.prod
        echo SECRET_KEY=${{ secrets.PROD_SECRET_KEY }} >> .env.prod
        echo DJANGO_ALLOWED_HOSTS=www.ubccourses.software >> .env.prod
        echo SQL_ENGINE=django.db.backends.postgresql >> .env.prod
        echo SQL_DATABASE=${{ secrets.PROD_SQL_DATABASE }} >> .env.prod
        echo SQL_USER=${{ secrets.PROD_SQL_USER }} >> .env.prod
        echo SQL_PASSWORD=${{ secrets.PROD_SQL_PASSWORD }} >> .env.prod
        echo SQL_HOST=${{ secrets.PROD_SQL_HOST }} >> .env.prod
        echo SQL_PORT=${{ secrets.PROD_SQL_PORT }} >> .env.prod
        echo DATABASE=postgres >> .env.prod
        echo VIRTUAL_HOST=www.ubccourses.software >> .env.prod
        echo VIRTUAL_PORT=8000 >> .env.prod
        echo LETSENCRYPT_HOST=www.ubccourses.software >> .env.prod

    - name: Build Docker images
      id: build-images
      run: |
        # Use docker-compose.prod.yml for deployment, or
        # docker-compose.staging.yml to test changes
        # - will fail if there are flake8 errors
        docker-compose -f docker-compose.staging.yml build

    - name: Configure AWS credentials
      id: login-aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to ECR
      id: login-ecr
      uses: docker/login-action@v1
      with:
        registry: 115646757360.dkr.ecr.us-east-2.amazonaws.com

    - name: Push images to ECR
      id: push-ecr
      run: |
        # Use docker-compose.prod.yml for deployment, or
        # docker-compose.staging.yml to test changes
        docker-compose -f docker-compose.staging.yml push

    # next, deploy on EC2 instance
